name: Paypay PHP Sample ecommerce backend CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 53af487a6fc0ad2f9ac01a7c1bb2fc641d7f70712f34a7f6e4bb054f7b0ff328
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
      - uses: actions/checkout@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: composer update
        run: composer update --lock
      - name: Run composer
        run: composer install      

      - name: Before script
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make run_mock
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coverall_upload

      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)

      - name: After build
        run: ./cc-test-reporter after-build --exit-code 0